### ISSUE TITLE
Failed to unlock "securefs" volume. Wrong password entered.

### ISSUE THREAD

**Issue by mpollov** [netheril96/securefs#119]
Volume created on Linux Fedora 34 with SiriKali. Sync with Yandex.disk. And try mount on Windows 10 with SiriKali.
Dialog with error text: 
![screenshot-securefs01](https://user-images.githubusercontent.com/87892203/126870398-c2d11c74-29c2-4346-be1c-bca5e2addfe5.png)
Try mount from command line get error: Invalid password

**Comment by netheril96** [comment]
Are you sure the password is correct and the securefs binary is the same
version?

**Comment by mpollov** [comment]
Password is correct i am sure.  But binary maybe different. On Fedora I build from sources. On WIndows use binaries from this releases.

**Comment by netheril96** [comment]
What commit did you build from source on Fedora?

Can you reproduce this issue with a repository containing non-sensitive data and throw away password and upload them?

**Comment by netheril96** [comment]
I added a [regression test](https://github.com/netheril96/securefs/blob/a4972834d93e89117e67dae58998f10f8a7c0fbb/test/simple_test.py#L426) specifically to catch this. So it is surprising to me.

**Comment by bsnipes** [comment]
I have the same issue. I typically run Linux and have an older securefs encrypted folder that hasn't been opened since mid-2019 that I just tried to open with securefs 0.11.1 on Arch Linux and it gives me the following error from the command line:

[Error] [0x7f397c3f3080] [2021-08-07 14:49:45.422495097 UTC] [int securefs::commands_main(int, const char* const*):1422]    Invalid password

However if I boot into Windows and use the securefs binary I had saved ( 0.90-beta1-34-g500fba1 ), it mounts the folder with no problems using the same password.

**Comment by bsnipes** [comment]
The attached doesn't work properly for me. Created with securefs 0.90-beta1-34-g500fba1 and cannot be opened with 0.11.1
Password is 'securefstest'.

[securefstest.zip](https://github.com/netheril96/securefs/files/6949302/securefstest.zip)

**Comment by netheril96** [comment]
Here is the latest build on Windows. Please try this.
[securefs.zip](https://github.com/netheril96/securefs/files/6950275/securefs.zip)

**Comment by bsnipes** [comment]
You new binary opened my older encrypted folder perfectly (along with the test one I had created).

**Comment by netheril96** [comment]
@mpollov Does the new binary fix your problem too?
