### ISSUE TITLE
Helpful FAQ

### ISSUE THREAD

**Issue by akarambir** [netheril96/securefs#14]
Hi, thank you for the great software. I wanted to ask some very simple questions as a user of this product which if you find helpful can put up in a wiki for others. I am not very well versed in Cryptography, so maybe some questions are already answered in README.

- Does having config file separately stored from the content helps against attackers(newbie version of #9 i think)? How much(its ok if you can only give your opinion on this)
- How much damage will occur if I lose some files in encrypted folder. My take: as it is block level encryption and have no information about files, this can impact some files depending on how those files were structured on file system.
- How compressing the encrypted content affects the content? Which compression tech/algo can be used safely?
- Can I(in future versions maybe) tell the (max or min)size of blocks to be generated? Let's say I want to generate files less than 1Mb.

Again, thanks for the awesome software 😄

**Comment by netheril96** [comment]
I'm glad that you find my software useful. I do not plan currently to set up a wiki since not many people have asked questions so there aren't really an estimation of frequency (as in *frequently* asked questions).

As for your questions:

* If an attacker does not have access to your config file, he/she cannot brute force your password. In fact, even if he/she knows the password, he/she cannot unlock the filesystem without the config file. The only possibility is to brute force the 256-bit master key, which, barring any weaknesses in Crypto++'s random number generator, is simply impossible. So basically, no access to config file, no access to the content. However, you may increase the risk of losing the config file yourself if you don't store it along with the content, and if you lose it, you will forever lose all the data you have encrypted.
* `securefs` is not a block level encryption system. It operates on the abstraction of files, not disk blocks. If you lose some files in the underlying storage, you need to run `securefs fix` to recover the directory structure. If the file you lose corresponds to a regular file in the virtual filesystem, you will simply lose the file. If it corresponds to a directory in the virtual filesystem, the *content* of files and directories in that directory will not be impacted, but their filenames will. **It is recommended that you backup your storage before you run the fix, as the fix command is not tested as often as other commands**.
* The reason that compression *may* leak information is that it alters data size, which is public knowledge in most crypto systems. It is a complicated matter. In fact, the file sizes may leak information even if no compression is present. It all depends on how much attackers know *a priori* about the content you store.
* I don't understand this last question.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.

**Comment by netheril96** [comment]
> About compression, I have a question. Since compression alters the original size of a file, why this might be an information link? Shouldn't the original file size provide "more" information instead?

See [CRIME attack](https://crashtest-security.com/prevent-ssl-crime/) and [Why is compression not recommended in OpenVPN?](https://superuser.com/questions/1686651/why-is-compression-not-recommended-in-openvpn)

It's not impossible to do compression + security correctly, but I have few experience with compression so I don't have confidence in doing that combination correctly.

If you really want compression + encryption, you can layer some other transparent compression FUSE on top of `securefs`.

**Comment by teras** [comment]
I got it. This again makes sense when communication is involved, but maybe not in the context of a filesystem layer where there is no knowledge of what is encrypted actually.

I totally understand your point of view about the confidence, especially in things dealing with encryption. I know that I can use something like fuse-zip, by putting a zip file inside the securefs encrypted folder, and it looks safe since zip is a common file format. If something goes bad, the file is still in zip format.

The problem with this approach is, all files will be inside a giant file, like in veracrypt. So no real gain here. I'd prefer the compression to be performed per-file, having again all these little things lying around, even easy to incrementally backup.

**Comment by netheril96** [comment]
I don't mean `fuse-zip`, but some fuse system that transparent compresses each file individually. To be more accurate, each block has to be independently compressed because fuse support random read-write. That compression ratio will be very unsatisfying.

**Comment by teras** [comment]
Our of curiosity I did some tests. I used zip on top of securefs, meaning that I had a securefs layer and inside I put a zip file and inside the files I wanted to test. My test was a 20MB file, that can be compressed to ~4.5MB. With this approach the securefs folder was about 4.6MB.

The other way around, to encrypt and then zip (or whatever) was very unsatisfying indeed, but also expected. The folder size was just above 20MB. But of course, this is what encryption is about.

That's why the ideal solution would have been, instead of treating any file stored inside securefs as "raw" data, to compress any file autonomously and encrypt this data block instead.

**Comment by netheril96** [comment]
The problem with transparent compressed writable filesystem is that each block must be separately compressed. That makes compression ratio unsatisfying. You are compressing a whole file, which is very different from block level compression. The latter won't have such drastic effects.
