### ISSUE TITLE
eCryptfs

### ISSUE THREAD

**Issue by alphapapa** [netheril96/securefs#3]
I just saw this on onethingwell.  It looks interesting.  Would you mind comparing it to eCryptfs?  Of course, eCryptfs is not a FUSE filesystem, but other than that, they seem comparable.

Of particular interest is performance.  For example, eCryptfs makes listing files in large directories quite slow, because it has to read the first part of each file (IIRC, to get the file's decrypted size).  There is no cache other than the kernel's page cache.  If securefs could help mitigate this problem while maintaining security and performance, it would be a big improvement.

**Comment by netheril96** [comment]
Sorry, the primary reason I write `securefs` is security, and that is its advantage over `eCryptfs` as well. `securefs` has no performance advantage when the number of files is large. It has read to each file to get its metadata as well. Frankly it may fare even worse because it also has to check the HMAC of each file's metadata. The only way to mitigate this problem is to give up the integrity guarantee.

**Comment by netheril96** [comment]
Now to think it, maybe I can store all the metadata centrally in a `SQLite3` database. That will reduce the strain on the filesystem as caching of a single file is better performant than a number of files. HMAC will still be slow though.

**Comment by netheril96** [comment]
I don't use `securefs` to encrypt my home directory; `FileVault` is enough for me. I only use `securefs` for mission critical data, especially those synced over the cloud. The design is different than eCryptfs.

**Comment by alphapapa** [comment]
Thanks for that explanation.  If you are so inclined, it would be interesting to read more about how its design compares with eCryptfs, other than performance-wise.

**Comment by netheril96** [comment]
The major advantage of `securefs` over `eCryptFs` is *ciphertext integrity* and *randomization*, as mentioned in the bottom of `README`. These two points are the whole reason I started this project, because when I learned cryptography, the professor said that these two are vital for any systems aiming to be secure, yet none of the existing solutions have them.

As for performance, `securefs` probably fares worse handling large amount of files, due to the need of integrity verification, but better when reading/writing files, because its encryption algorithm is `AES-GCM`, where `eCryptFs` has `AES-CBC`. The former is faster and can be hardware accelerated (if you CPU has the corresponding instructions). On my machine, streaming read/write from `securefs` filesystem is about 170MiB/s. I haven't tested `eCryptFs` though so this is just a guess.

Another difference is that the underlying storage of `securefs` is flattened, that is, the virtual directory structure is not visible, because `securefs` implements its own directory file.

The filename limit of `securefs` is 255, regardless of the underlying filesystem, while `eCryptFs` may have less.

**Comment by alphapapa** [comment]
> Another difference is that the underlying storage of securefs is flattened, that is, the virtual directory structure is not visible, because securefs implements its own directory file.

Sorry, I don't understand what you mean here.  Does this mean that it doesn't support subdirectories?  Or does it mean that it stores all underlying files in one directory and provides its own implementation of directories?

**Comment by netheril96** [comment]
You could just clone the repo, compile it and see it yourself.

**Comment by netheril96** [comment]
A critical security vulnerability has been found in securefs version 0.4.0 to 0.6.0. If you have used these version to encrypt your data, please either migrate to the newest version or some other encryption software.
