### ISSUE TITLE
Mounted folder is empty

### ISSUE THREAD

**Issue by Zhomart** [netheril96/securefs#33]
After upgrading OS to 10.12.3, securefs started working. But now it doesn't show files in mounted directory.

1. I created secure folder `securefs create Asd`
2. I've mounted it `securefs mount -v Asd Qwe`
3. `cp image.jpg Qwe/image.jpg`
4. `ls -la Qwe/`, it's empty
5. `ls -la Asd/`, I see that new file is created

Same with directories. But sometimes after re-mounting I see files in mounted dir `Qwe`.

```
$ securefs version
securefs 0.7.2
Crypto++ 5.65
osxfuse 3.5.6

Hardware features available:
SSE2: true
SSE3: true
SSE4: true
AES-NI: true
CLMUL: true
```

**Comment by netheril96** [comment]
Do you rebuild securefs after OS upgrade? Is there any log output from `securefs` when you run `ls -la Qwe/`?

**Comment by Zhomart** [comment]
@netheril96 Thank you for responding. Now suddenly I cannot replicate it. But as I remember, I didn't see any message on console.

Also, when I copy directories/files, sometimes it throws permission denied error. But second time I copy, it's ok. No logs too on console.

**Comment by netheril96** [comment]
What exactly is permission denied? Opening, reading, writing, or extended attributes?

**Comment by Zhomart** [comment]
`... could not copy extended attributes to ... : Permission denied`.

**Comment by netheril96** [comment]
It is expected behavior, likely caused by https://github.com/netheril96/securefs/blob/master/sources/lite_operations.cpp#L467. It simply means that the extended attribute `com.apple.FinderInfo` is not copied (its size is hardcoded by the stupid Apple, and therefore it cannot be encrypted since an IV and tag must be added to the ciphertext). Other extended attributes and the file data itself are copied successfully nonetheless.

I haven't found any use of this FinderInfo. If you really want it, you can mount with option `-x`. This will create `._files` to store the extended attributes instead. I personally hate those dot files.

**Comment by Zhomart** [comment]
@netheril96 I never check if file is copied or not. It's copied! :) Thank you for explaining it.
