### ISSUE TITLE
securefs full on cifs is extremely slow

### ISSUE THREAD

**Issue by Thermi** [netheril96/securefs#97]
The underlying FS is on a CIFS share mounted over the WAN with seal (authentication and encryption) enabled. I suspect the problem is lots of stats or something that similiarly small that takes some milliseconds over the WAN, but significantly shorter on local storage, which makes it significantly slower.
The rate is absurdly low. I've been doing a backup of 180G over the last week and it isn't finished yet.
Observed data rate over the WAN was significantly below 1 MBit/s, but bandwidth is at least 100 Mbit/s, if not 1 GBIt/s. CPU load is also nearly nonexistent.

**Comment by netheril96** [comment]
How many files do you have?

**Comment by Thermi** [comment]
About 2365574.

**Comment by netheril96** [comment]
The full format is indeed slow for many small files. Each file operation takes multiple syscalls, so that is the bottleneck. That is inherent to the design of full format.

How are you doing your backup? Are you mounting a securefs repo on a network volume and copy your unencrypted files onto that repo?

In my case, I have a local repo, and I just backup the local repo over the Internet, so there is no involvement of `securefs` in network.

**Comment by bitraid** [comment]
Maybe this doesn't apply here, but on another project they managed to imporve the (reading) speed of a mounted cifs share by using `fstat` instead of `lseek` for getting the filesize:
https://github.com/netheril96/securefs/blob/344c46e34900f65c0bbc9c23db22155189e656a3/sources/unix.cpp#L132-L138
I tried it and did some tests with `cifsiostat` but i didn't notice much improvement (but my speed was fast to begin with).

**Comment by Thermi** [comment]
> The full format is indeed slow for many small files. Each file operation takes multiple syscalls, so that is the bottleneck. That is inherent to the design of full format.
> 
> How are you doing your backup? Are you mounting a securefs repo on a network volume and copy your unencrypted files onto that repo?
> 

Yes, exactly. I am doing a full system backup to a rented storage space.

**Comment by netheril96** [comment]
> Maybe this doesn't apply here, but on another project they managed to imporve the (reading) speed of a mounted cifs share by using `fstat` instead of `lseek` for getting the filesize:
> https://github.com/netheril96/securefs/blob/344c46e34900f65c0bbc9c23db22155189e656a3/sources/unix.cpp#L132-L138
> 
> 
> I tried it and did some tests with `cifsiostat` but i didn't notice much improvement (but my speed was fast to begin with).

Good suggestion. Implemented in 3e167a13abcde00e79516dac1e6af49c5f411a5d

**Comment by netheril96** [comment]
> > The full format is indeed slow for many small files. Each file operation takes multiple syscalls, so that is the bottleneck. That is inherent to the design of full format.
> > How are you doing your backup? Are you mounting a securefs repo on a network volume and copy your unencrypted files onto that repo?
> 
> Yes, exactly. I am doing a full system backup to a rented storage space.

What is your OS? Linux will perform faster than macOS, and significantly faster than Windows.

There is really not much I can do to fundamentally speed up securefs in format 2, which is why I introduced format 4 in the first place. You have the following options:

* Use format 4 instead of format 2
* Create a local repo on a NTFS volume, mount it with securefs, copy all the files into that mounted filesystem, unmount it, and then copy the encrypted files to your network storage. For incremental updates you can just mount the remote repo directly like you do now.

**Comment by Thermi** [comment]
Linux. Local FS is XFS. I don't have enough space for a full second copy of the data, so that's a no-go.

**Comment by netheril96** [comment]
Nothing more I could do. You may try if that latest commit speed things up.

**Comment by Thermi** [comment]
I tested the commit and it significantly speeds up the transfer. :)

**Comment by Thermi** [comment]
Update: On NFS, it's significantly faster. Factor >>> 6.

**Comment by netheril96** [comment]
> Update: On NFS, it's significantly faster. Factor >>> 6.

Thanks to @bitraid

**Comment by bitraid** [comment]
Glad i could help. Actual credit goes to @wm4 for figuring this out, and @LennertVA for reporting and running the tests: https://github.com/mpv-player/mpv/issues/7408
